Add cross-environment section to the areas of general agreement
patcg/docs-and-reports pull request #47
Opened 2023-06-16 09:45 UTC by csharrison

2023-06-16 10:47 UTC, michaelkleber requested changes

2023-06-16 10:47 UTC, michaelkleber commented on design-dimensions/Dimensions-with-General-Agreement.md
> +Note: the precise details of _how_ these events are joined and measured needs to be separately agreed upon. The current consensus only documents an agreement that joins across computing environments
I think we can avoid sounding so double-negative here.

```suggestion
Note: the precise details of _how_ these events are joined and measured needs to be separately agreed upon. The current consensus documents an agreement that the group is open to designs that support joins across environments.
```

2023-08-22 16:16 UTC, csharrison commented
@AramZS can you please give next steps for this PR

2023-10-30 17:46 UTC, AramZS commented
As discussed, these PRs have been open long enough to acquire consensus that they accurately describe our conversations.

2023-10-30 17:46 UTC, merged